### ISSUE TITLE
关于Ajax的Delete方法

### ISSUE THREAD

**Issue by CoderIvan** [zkboys/ra-lib#1]
在使用阿里的CDN产品时发现，阿里的CDN会拦截含有body的delete请求
<img width="315" alt="5fefe7fa5f35465b2ed171f58e2928c" src="https://user-images.githubusercontent.com/7960859/129851103-838e32a4-b77f-4efb-82dc-69999e88c1e5.png">

![image](https://user-images.githubusercontent.com/7960859/129851458-c70feeb1-454d-4116-83f9-155a13476f30.png)

这个地方是不是能规范一下？当然我也觉得阿里CDN的拦截也是有点多管闲事了

**Comment by zkboys** [comment]
你说的这个问题已经解决了，请安装最新版本 @ra-lib/ajsx 或 @ra-lib/admin
另外，这个库迁移了，不久会删除，请移步： [https://github.com/sxfad/ra-lib](https://github.com/sxfad/ra-lib)

**Comment by CoderIvan** [comment]
好的，感谢回复
